swagger_ui_page.swagger:
  path: '/swagger'
  defaults:
    _controller: '\Drupal\swagger_ui_page\Controller\SwaggerUIController::content'
    _title: 'Swagger UI'
  requirements:
    _permission: 'access content'
